version: "3.9"
   
services:
  api_gateway_db:
    build: 
      context: ./api_gateway
      dockerfile: Dockerfile.postgres
    restart: on-failure
    ports:
      - "5436:5432"
    volumes:
      - api_gateway_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${API_GATEWAY_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${API_GATEWAY_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${API_GATEWAY_POSTGRES_DB}"
  api_gateway_api:
    build: ./api_gateway
    restart: on-failure
    command: /bin/api_gateway
    volumes:
      - .:/app
    ports:
      - "2718:2718"
    depends_on:
      - api_gateway_db

  product_db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3307:3306"
    volumes:
      - product_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${PRODUCT_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${PRODUCT_MYSQL_DATABASE}"
      MYSQL_USER: "${PRODUCT_MYSQL_USER}"
      MYSQL_PASSWORD: "${PRODUCT_MYSQL_PASSWORD}"
  product_api:
    build: ./product
    restart: on-failure
    command: /bin/product
    volumes:
      - .:/app
    ports:
      - "2719:2719"
    depends_on:
      - product_db

  cart_db:
    build: 
      context: ./cart
      dockerfile: Dockerfile.postgres
    restart: on-failure
    ports:
      - "5437:5432"
    volumes:
      - cart_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${CART_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${CART_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${CART_POSTGRES_DB}"
  cart_api:
    build: ./cart
    restart: on-failure
    command: /bin/cart
    volumes:
      - .:/app
    ports:
      - "2720:2720"
    depends_on:
      - cart_db

  order_db:
    build: 
      context: ./order
      dockerfile: Dockerfile.postgres
    restart: on-failure
    ports:
      - "5438:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${ORDER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${ORDER_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${ORDER_POSTGRES_DB}"
  order_api:
    build: ./order
    restart: on-failure
    command: /bin/order
    volumes:
      - .:/app
    ports:
      - "2721:2721"
    depends_on:
      - order_db

volumes:
  api_gateway_db_data: {}
  product_db_data: {}
  cart_db_data: {}
  order_db_data: {}
